defaults:
  - experiment: exp1
  - dataset: smnist
  - _self_

wandb: False #Avoid logging to wandb

# Avoid logging to folders
hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: False
  sweep:
    dir: .